### ISSUE TITLE
Sensor Height

### ISSUE THREAD

**Issue by haider8645** [robot-pesg/BotanicGarden#6]
Hello!

could you please tell me the sensor height of the Velodyne VLP-16 during data collection?

Best regards,
Haider

**Comment by robot-pesg** [comment]
@haider8645 

The transformation matrix of VLP-16 LiDAR center in Robot bottom plane (ground) is:

T_gnd_vlp =

   0.999678872580465   0.025286566442932   0.001504222922349   0.085736778152775
  -0.025272343896077   0.999649431893338  -0.007802543414159   0.003704199667663
  -0.001701039294055   0.007762982379262   0.999967893719160   1.163575521980526
                   0                   0                   0   1.000000000000000

indicating that the height of VLP-16 with respect to ground is around 1.164m

**Comment by haider8645** [comment]
Thanks!!
